"use server";

import { randomBytes } from "node:crypto";
import QRCode from "qrcode";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { getSupabaseEnv } from "@/lib/supabase/env";

export type ClaimKitState = {
  error: string | null;
  kit: {
    claimCode: string;
    claimUrl: string;
    expiresAt: string | null;
    firmwareConfig: string;
    kitManifest: string;
    localCheckCommand: string;
    raisedWheelCheckCommand: string;
    qrDataUrl: string;
    robotId: string;
    unitCode: string;
  } | null;
  ok: boolean;
};

export type HardwareProfileState = {
  error: string | null;
  ok: boolean;
};

export type BenchTestState = {
  error: string | null;
  ok: boolean;
};

const initialClaimKitState: ClaimKitState = {
  error: null,
  kit: null,
  ok: false,
};

const initialHardwareProfileState: HardwareProfileState = {
  error: null,
  ok: false,
};

const initialBenchTestState: BenchTestState = {
  error: null,
  ok: false,
};

function actionErrorMessage(message: string) {
  if (message.includes("admin_required")) return "This account is not in app_admins yet.";
  if (message.includes("duplicate_unit_code")) return "This unit code already has a claim kit.";
  if (message.includes("invalid_robot_type")) return "Choose a supported robot type.";
  if (message.includes("invalid_unit_code")) return "Enter a unit code such as RF-RV-0001.";
  if (message.includes("login_required")) return "Login is required.";
  return message;
}

async function getBaseUrl() {
  const { appUrl } = getSupabaseEnv();
  if (appUrl) return appUrl;

  const requestHeaders = await headers();
  const host =
    requestHeaders.get("x-forwarded-host") ?? requestHeaders.get("host") ?? "";
  const protocol = requestHeaders.get("x-forwarded-proto") ?? "https";

  if (!host) return "http://localhost:3000";
  return `${protocol}://${host}`;
}

function formValue(formData: FormData, key: string) {
  const value = formData.get(key);
  return typeof value === "string" ? value.trim() : "";
}

function formBoolean(formData: FormData, key: string) {
  return formData.get(key) === "on";
}

function normalizeRobotType(value: string) {
  const normalized = value.trim().toLowerCase();
  return ["rover", "tracked", "drone", "arm"].includes(normalized)
    ? normalized
    : "rover";
}

function normalizeFirmwareVersion(value: string) {
  return value.trim() || "0.1.0";
}

function normalizeBatteryChemistry(value: string) {
  const normalized = value.trim().toLowerCase();
  return ["li-ion", "lipo", "nimh", "alkaline", "unknown"].includes(normalized)
    ? normalized
    : "";
}

function normalizeMotorChannels(value: string) {
  const normalized = value.trim();
  return [
    "differential_drive",
    "tracked_drive",
    "single_motor",
    "custom",
  ].includes(normalized)
    ? normalized
    : "";
}

function normalizeWiringStatus(value: string) {
  const normalized = value.trim();
  return ["draft", "photo_received", "bench_verified"].includes(normalized)
    ? normalized
    : "";
}

function normalizeReadinessStatus(value: string) {
  const normalized = value.trim();
  return [
    "needs_details",
    "ready_for_bench",
    "ready_for_raised_wheels",
    "ready_for_floor",
    "blocked",
  ].includes(normalized)
    ? normalized
    : "needs_details";
}

function normalizeBenchStage(value: string) {
  const normalized = value.trim();
  return ["bench", "raised_wheels", "floor"].includes(normalized)
    ? normalized
    : "bench";
}

function normalizeBenchResult(value: string) {
  const normalized = value.trim();
  return ["pending", "passed", "failed", "blocked"].includes(normalized)
    ? normalized
    : "pending";
}

function sanitizeDefineValue(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function generateApPassword(unitCode: string) {
  const suffix = randomBytes(4).toString("hex").toUpperCase();
  const compactUnit = unitCode.replace(/[^A-Z0-9]/g, "").slice(-6) || "ROVER";
  return `forge-${compactUnit}-${suffix}`;
}

function buildFirmwareConfig(input: {
  apPassword: string;
  batteryCells: number;
  firmwareVersion: string;
  robotType: string;
  unitCode: string;
}) {
  return [
    "#pragma once",
    "",
    "// Generated by RoboForge Ops for this physical Beta kit.",
    `#define ROBOFORGE_UNIT_CODE "${sanitizeDefineValue(input.unitCode)}"`,
    `#define ROBOFORGE_AP_PASSWORD "${sanitizeDefineValue(input.apPassword)}"`,
    `#define ROBOFORGE_BATTERY_CELLS ${input.batteryCells}`,
    "#define ROBOFORGE_BATTERY_CALIBRATION 1.000f",
    `#define ROBOFORGE_FIRMWARE_VERSION "${sanitizeDefineValue(input.firmwareVersion)}"`,
    "#define ROBOFORGE_PROTOCOL_VERSION \"v1\"",
    `#define ROBOFORGE_ROBOT_TYPE "${sanitizeDefineValue(input.robotType)}"`,
    "",
    "// Rover-01 standardized wiring.",
    "#define ROBOFORGE_PIN_ENA 25",
    "#define ROBOFORGE_PIN_IN1 26",
    "#define ROBOFORGE_PIN_IN2 27",
    "#define ROBOFORGE_PIN_ENB 33",
    "#define ROBOFORGE_PIN_IN3 32",
    "#define ROBOFORGE_PIN_IN4 14",
    "#define ROBOFORGE_PIN_BATTERY_ADC 34",
  ].join("\n");
}

function buildKitManifest(input: {
  apPassword: string;
  apSsid: string;
  batteryCells: number;
  batteryChemistry: string;
  boardType: string;
  claimCode: string;
  claimUrl: string;
  firmwareVersion: string;
  hasFuse: boolean;
  hasPowerSwitch: boolean;
  motorChannels: string;
  motorDriver: string;
  robotId: string;
  robotType: string;
  unitCode: string;
  wiringNotes: string;
  wiringStatus: string;
}) {
  return [
    `RoboForge Beta Kit: ${input.unitCode}`,
    "",
    `Robot ID: ${input.robotId}`,
    `Robot type: ${input.robotType}`,
    `Board: ${input.boardType}`,
    `Motor driver: ${input.motorDriver}`,
    `Motor channels: ${input.motorChannels}`,
    `Firmware: ${input.firmwareVersion}`,
    "Protocol: v1",
    `Battery: ${input.batteryChemistry} / ${input.batteryCells}S`,
    `Wiring status: ${input.wiringStatus}`,
    `Wiring notes: ${input.wiringNotes}`,
    `Power switch: ${input.hasPowerSwitch ? "present" : "missing"}`,
    `Fuse/protected pack: ${input.hasFuse ? "present" : "missing"}`,
    `Local Wi-Fi SSID: ${input.apSsid}`,
    `Local Wi-Fi password: ${input.apPassword}`,
    "",
    "Owner claim:",
    input.claimUrl,
    input.claimCode,
    "",
    "Flash checklist:",
    "1. Paste the generated config into firmware/include/config.h.",
    "2. From app/, run npm run build:device.",
    "3. From firmware/, run pio run --target upload and pio run --target uploadfs.",
    "4. Join the robot Wi-Fi and run the non-driving protocol check.",
    "5. Raise the wheels before running the drive check.",
    "",
    "Note: the generated config is for the current ESP32 Rover firmware. If this",
    "kit uses another board, keep the claim code but implement docs/ROBOT_PROTOCOL.md",
    "on that board before running the Cockpit.",
  ].join("\n");
}

export async function createClaimKitAction(
  _previousState: ClaimKitState,
  formData: FormData,
): Promise<ClaimKitState> {
  const supabase = await createServerSupabaseClient();

  if (!supabase) {
    return {
      ...initialClaimKitState,
      error: "Supabase is not configured.",
    };
  }

  const expiresAtValue = formValue(formData, "expiresAt");
  const expiresAtDate = expiresAtValue ? new Date(expiresAtValue) : null;

  if (expiresAtDate && Number.isNaN(expiresAtDate.getTime())) {
    return {
      ...initialClaimKitState,
      error: "Choose a valid expiry date.",
    };
  }

  const expiresAt = expiresAtDate ? expiresAtDate.toISOString() : null;
  const boardType = formValue(formData, "boardType");
  const batteryCells = Number(formValue(formData, "batteryCells") || "2");
  const batteryChemistry = normalizeBatteryChemistry(
    formValue(formData, "batteryChemistry"),
  );
  const motorChannels = normalizeMotorChannels(formValue(formData, "motorChannels"));
  const motorDriver = formValue(formData, "motorDriver");
  const robotType = normalizeRobotType(formValue(formData, "robotType") || "rover");
  const firmwareVersion = normalizeFirmwareVersion(formValue(formData, "firmwareVersion"));
  const wiringNotes = formValue(formData, "wiringNotes");
  const wiringStatus = normalizeWiringStatus(formValue(formData, "wiringStatus"));
  const hasFuse = formBoolean(formData, "hasFuse");
  const hasPowerSwitch = formBoolean(formData, "hasPowerSwitch");

  if (![1, 2].includes(batteryCells)) {
    return {
      ...initialClaimKitState,
      error: "Choose 1S or 2S for the first Rover beta firmware.",
    };
  }

  if (!boardType || !motorDriver || !batteryChemistry || !motorChannels || !wiringStatus) {
    return {
      ...initialClaimKitState,
      error:
        "Board, motor driver, battery, motor channels, and wiring status are required before creating a physical kit.",
    };
  }

  if (!wiringNotes) {
    return {
      ...initialClaimKitState,
      error: "Add a wiring photo link or pin list before creating a physical kit.",
    };
  }

  if (!hasPowerSwitch || !hasFuse) {
    return {
      ...initialClaimKitState,
      error:
        "Add an accessible power switch and a fuse or protected battery pack before creating a physical kit.",
    };
  }

  const requestedApPassword = formValue(formData, "apPassword");

  if (
    requestedApPassword &&
    (requestedApPassword.length < 8 || requestedApPassword.length > 63)
  ) {
    return {
      ...initialClaimKitState,
      error: "Wi-Fi AP password must be 8-63 characters.",
    };
  }

  const { data, error } = await supabase.rpc("create_robot_claim_kit", {
    input_board_type: boardType,
    input_display_name: formValue(formData, "displayName") || null,
    input_expires_at: expiresAt,
    input_firmware_version: firmwareVersion,
    input_robot_type: robotType,
    input_unit_code: formValue(formData, "unitCode"),
  });

  if (error) {
    return {
      ...initialClaimKitState,
      error: actionErrorMessage(error.message),
    };
  }

  const kit = data as {
    claimCode: string;
    expiresAt: string | null;
    robotId: string;
    unitCode: string;
  };
  const apPassword = requestedApPassword || generateApPassword(kit.unitCode);
  const apSsid = `RoboForge-${kit.unitCode}`.slice(0, 31);
  const claimUrl = `${await getBaseUrl()}/dashboard?claim=${encodeURIComponent(
    kit.claimCode,
  )}`;
  const qrDataUrl = await QRCode.toDataURL(claimUrl, {
    errorCorrectionLevel: "M",
    margin: 2,
    width: 320,
  });

  const firmwareConfig = buildFirmwareConfig({
    apPassword,
    batteryCells,
    firmwareVersion,
    robotType,
    unitCode: kit.unitCode,
  });
  const localCheckCommand =
    "node scripts/rover-protocol-check.mjs --base-url=http://192.168.4.1";
  const raisedWheelCheckCommand = "node scripts/rover-protocol-check.mjs --raised-wheels";
  const kitManifest = buildKitManifest({
    apPassword,
    apSsid,
    batteryCells,
    batteryChemistry,
    boardType,
    claimCode: kit.claimCode,
    claimUrl,
    firmwareVersion,
    hasFuse,
    hasPowerSwitch,
    motorChannels,
    motorDriver,
    robotId: kit.robotId,
    robotType,
    unitCode: kit.unitCode,
    wiringNotes,
    wiringStatus,
  });

  const hardwareProfile = {
    batteryCells,
    batteryChemistry,
    boardModel: boardType,
    hasFuse,
    hasPowerSwitch,
    motorChannels,
    motorDriver,
    notes: wiringNotes,
    wiringStatus,
  };

  const { error: deviceUpdateError } = await supabase
    .from("robot_devices")
    .update({
      ap_ssid: apSsid,
      battery_config: {
        calibration: 1,
        chemistry: batteryChemistry,
        cells: batteryCells,
      },
      board_type: boardType,
      firmware_version: firmwareVersion,
      hardware_profile: hardwareProfile,
      protocol_version: "v1",
      readiness_status: "ready_for_bench",
      updated_at: new Date().toISOString(),
    })
    .eq("robot_id", kit.robotId);

  revalidatePath("/admin");

  return {
    error: deviceUpdateError
      ? `Claim kit was created, but device metadata did not update: ${deviceUpdateError.message}`
      : null,
    kit: {
      ...kit,
      claimUrl,
      firmwareConfig,
      kitManifest,
      localCheckCommand,
      raisedWheelCheckCommand,
      qrDataUrl,
    },
    ok: true,
  };
}

export async function saveHardwareProfileAction(
  _previousState: HardwareProfileState,
  formData: FormData,
): Promise<HardwareProfileState> {
  const supabase = await createServerSupabaseClient();

  if (!supabase) {
    return {
      ...initialHardwareProfileState,
      error: "Supabase is not configured.",
    };
  }

  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return {
      ...initialHardwareProfileState,
      error: "Login is required.",
    };
  }

  const robotId = formValue(formData, "robotId");

  if (!robotId) {
    return {
      ...initialHardwareProfileState,
      error: "Choose a robot kit first.",
    };
  }

  const batteryCells = Number(formValue(formData, "batteryCells") || "0");
  const readinessStatus = normalizeReadinessStatus(
    formValue(formData, "readinessStatus"),
  );
  const hardwareProfile = {
    batteryCells: Number.isFinite(batteryCells) && batteryCells > 0 ? batteryCells : null,
    batteryChemistry: formValue(formData, "batteryChemistry") || null,
    boardModel: formValue(formData, "boardModel") || null,
    hasFuse: formBoolean(formData, "hasFuse"),
    hasPowerSwitch: formBoolean(formData, "hasPowerSwitch"),
    motorChannels: formValue(formData, "motorChannels") || "differential_drive",
    motorDriver: formValue(formData, "motorDriver") || null,
    notes: formValue(formData, "notes") || null,
    wiringStatus: formValue(formData, "wiringStatus") || "unknown",
  };

  const missingRequired = [
    hardwareProfile.boardModel,
    hardwareProfile.motorDriver,
    hardwareProfile.batteryChemistry,
    hardwareProfile.batteryCells,
  ].some((value) => !value);

  if (
    readinessStatus !== "needs_details" &&
    readinessStatus !== "blocked" &&
    missingRequired
  ) {
    return {
      ...initialHardwareProfileState,
      error:
        "Board, motor driver, battery chemistry, and cell count are required before marking the kit ready.",
    };
  }

  const { error } = await supabase
    .from("robot_devices")
    .update({
      battery_config: {
        chemistry: hardwareProfile.batteryChemistry,
        cells: hardwareProfile.batteryCells,
      },
      board_type: hardwareProfile.boardModel ?? "unknown",
      hardware_profile: hardwareProfile,
      readiness_status: readinessStatus,
      updated_at: new Date().toISOString(),
    })
    .eq("robot_id", robotId);

  if (error) {
    return {
      ...initialHardwareProfileState,
      error: error.message,
    };
  }

  await supabase.from("robot_events").insert({
    event_type: "hardware_profile_updated",
    message: `Ops updated hardware profile: ${readinessStatus}.`,
    metadata: hardwareProfile,
    robot_id: robotId,
    severity: readinessStatus === "blocked" ? "warning" : "info",
    user_id: user.id,
  });

  revalidatePath("/admin");

  return {
    error: null,
    ok: true,
  };
}

const checkLabels = {
  apVisible: "Robot Wi-Fi appears",
  armOk: "Arm command works",
  batteryVisible: "Battery/status is visible",
  emergencyStopOk: "Emergency stop works",
  floorClear: "Floor path is clear",
  infoOk: "Info endpoint works",
  lowSpeedDriveOk: "Low-speed drive works",
  powerOn: "Robot powers on",
  shortFloorDriveOk: "Short floor drive works",
  statusOk: "Status endpoint works",
  stopOk: "Stop endpoint works",
  wheelsRaised: "Wheels are raised",
  wifiJoined: "Phone/computer joins robot Wi-Fi",
  zeroReleaseOk: "Release-to-zero stops the robot",
} as const;

const requiredBenchChecks = [
  "powerOn",
  "apVisible",
  "wifiJoined",
  "infoOk",
  "statusOk",
  "stopOk",
] as const;

const requiredRaisedWheelChecks = [
  ...requiredBenchChecks,
  "wheelsRaised",
  "armOk",
  "lowSpeedDriveOk",
  "zeroReleaseOk",
  "emergencyStopOk",
] as const;

const requiredFloorChecks = [
  ...requiredRaisedWheelChecks,
  "floorClear",
  "shortFloorDriveOk",
] as const;

function buildBenchChecks(formData: FormData) {
  return {
    apVisible: formBoolean(formData, "apVisible"),
    armOk: formBoolean(formData, "armOk"),
    batteryVisible: formBoolean(formData, "batteryVisible"),
    emergencyStopOk: formBoolean(formData, "emergencyStopOk"),
    floorClear: formBoolean(formData, "floorClear"),
    infoOk: formBoolean(formData, "infoOk"),
    lowSpeedDriveOk: formBoolean(formData, "lowSpeedDriveOk"),
    powerOn: formBoolean(formData, "powerOn"),
    shortFloorDriveOk: formBoolean(formData, "shortFloorDriveOk"),
    statusOk: formBoolean(formData, "statusOk"),
    stopOk: formBoolean(formData, "stopOk"),
    wheelsRaised: formBoolean(formData, "wheelsRaised"),
    wifiJoined: formBoolean(formData, "wifiJoined"),
    zeroReleaseOk: formBoolean(formData, "zeroReleaseOk"),
  };
}

function requiredChecksForStage(stage: string) {
  if (stage === "floor") return requiredFloorChecks;
  if (stage === "raised_wheels") return requiredRaisedWheelChecks;
  return requiredBenchChecks;
}

function readinessAfterBenchTest(stage: string, result: string) {
  if (result === "blocked" || result === "failed") return "blocked";
  if (result !== "passed") return null;
  if (stage === "bench") return "ready_for_raised_wheels";
  return "ready_for_floor";
}

export async function saveBenchTestAction(
  _previousState: BenchTestState,
  formData: FormData,
): Promise<BenchTestState> {
  const supabase = await createServerSupabaseClient();

  if (!supabase) {
    return {
      ...initialBenchTestState,
      error: "Supabase is not configured.",
    };
  }

  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return {
      ...initialBenchTestState,
      error: "Login is required.",
    };
  }

  const robotId = formValue(formData, "robotId");

  if (!robotId) {
    return {
      ...initialBenchTestState,
      error: "Choose a robot kit first.",
    };
  }

  const stage = normalizeBenchStage(formValue(formData, "stage"));
  const result = normalizeBenchResult(formValue(formData, "result"));
  const checks = buildBenchChecks(formData);
  const notes = formValue(formData, "notes") || null;

  if (result === "passed") {
    const missingChecks = requiredChecksForStage(stage).filter(
      (check) => !checks[check],
    );

    if (missingChecks.length > 0) {
      return {
        ...initialBenchTestState,
        error: `Before marking this as passed, complete: ${missingChecks
          .map((check) => checkLabels[check] ?? check)
          .join(", ")}.`,
      };
    }
  }

  const { error } = await supabase.from("robot_bench_tests").insert({
    checks,
    notes,
    result,
    robot_id: robotId,
    stage,
    user_id: user.id,
  });

  if (error) {
    return {
      ...initialBenchTestState,
      error: error.message,
    };
  }

  const readinessStatus = readinessAfterBenchTest(stage, result);

  if (readinessStatus) {
    await supabase
      .from("robot_devices")
      .update({
        readiness_status: readinessStatus,
        updated_at: new Date().toISOString(),
      })
      .eq("robot_id", robotId);
  }

  await supabase.from("robot_events").insert({
    event_type: "bench_test_recorded",
    message: `Ops recorded ${stage} test as ${result}.`,
    metadata: {
      checks,
      notes,
      result,
      stage,
    },
    robot_id: robotId,
    severity: result === "failed" || result === "blocked" ? "warning" : "info",
    user_id: user.id,
  });

  revalidatePath("/admin");

  return {
    error: null,
    ok: true,
  };
}
