"use server";

import { randomBytes } from "node:crypto";
import QRCode from "qrcode";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export type ClaimKitState = {
  error: string | null;
  kit: {
    claimCode: string;
    claimUrl: string;
    expiresAt: string | null;
    firmwareConfig: string;
    kitManifest: string;
    localCheckCommand: string;
    raisedWheelCheckCommand: string;
    qrDataUrl: string;
    robotId: string;
    unitCode: string;
  } | null;
  ok: boolean;
};

export type HardwareProfileState = {
  error: string | null;
  ok: boolean;
};

const initialClaimKitState: ClaimKitState = {
  error: null,
  kit: null,
  ok: false,
};

const initialHardwareProfileState: HardwareProfileState = {
  error: null,
  ok: false,
};

function actionErrorMessage(message: string) {
  if (message.includes("admin_required")) return "This account is not in app_admins yet.";
  if (message.includes("duplicate_unit_code")) return "This unit code already has a claim kit.";
  if (message.includes("invalid_robot_type")) return "Choose a supported robot type.";
  if (message.includes("invalid_unit_code")) return "Enter a unit code such as RF-RV-0001.";
  if (message.includes("login_required")) return "Login is required.";
  return message;
}

async function getBaseUrl() {
  const requestHeaders = await headers();
  const host =
    requestHeaders.get("x-forwarded-host") ?? requestHeaders.get("host") ?? "";
  const protocol = requestHeaders.get("x-forwarded-proto") ?? "https";

  if (!host) return "http://localhost:3000";
  return `${protocol}://${host}`;
}

function formValue(formData: FormData, key: string) {
  const value = formData.get(key);
  return typeof value === "string" ? value.trim() : "";
}

function formBoolean(formData: FormData, key: string) {
  return formData.get(key) === "on";
}

function normalizeRobotType(value: string) {
  const normalized = value.trim().toLowerCase();
  return ["rover", "tracked", "drone", "arm"].includes(normalized)
    ? normalized
    : "rover";
}

function normalizeFirmwareVersion(value: string) {
  return value.trim() || "0.1.0";
}

function normalizeReadinessStatus(value: string) {
  const normalized = value.trim();
  return [
    "needs_details",
    "ready_for_bench",
    "ready_for_raised_wheels",
    "ready_for_floor",
    "blocked",
  ].includes(normalized)
    ? normalized
    : "needs_details";
}

function sanitizeDefineValue(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function generateApPassword(unitCode: string) {
  const suffix = randomBytes(4).toString("hex").toUpperCase();
  const compactUnit = unitCode.replace(/[^A-Z0-9]/g, "").slice(-6) || "ROVER";
  return `forge-${compactUnit}-${suffix}`;
}

function buildFirmwareConfig(input: {
  apPassword: string;
  batteryCells: number;
  firmwareVersion: string;
  robotType: string;
  unitCode: string;
}) {
  return [
    "#pragma once",
    "",
    "// Generated by RoboForge Ops for this physical Beta kit.",
    `#define ROBOFORGE_UNIT_CODE "${sanitizeDefineValue(input.unitCode)}"`,
    `#define ROBOFORGE_AP_PASSWORD "${sanitizeDefineValue(input.apPassword)}"`,
    `#define ROBOFORGE_BATTERY_CELLS ${input.batteryCells}`,
    "#define ROBOFORGE_BATTERY_CALIBRATION 1.000f",
    `#define ROBOFORGE_FIRMWARE_VERSION "${sanitizeDefineValue(input.firmwareVersion)}"`,
    "#define ROBOFORGE_PROTOCOL_VERSION \"v1\"",
    `#define ROBOFORGE_ROBOT_TYPE "${sanitizeDefineValue(input.robotType)}"`,
    "",
    "// Rover-01 standardized wiring.",
    "#define ROBOFORGE_PIN_ENA 25",
    "#define ROBOFORGE_PIN_IN1 26",
    "#define ROBOFORGE_PIN_IN2 27",
    "#define ROBOFORGE_PIN_ENB 33",
    "#define ROBOFORGE_PIN_IN3 32",
    "#define ROBOFORGE_PIN_IN4 14",
    "#define ROBOFORGE_PIN_BATTERY_ADC 34",
  ].join("\n");
}

function buildKitManifest(input: {
  apPassword: string;
  apSsid: string;
  batteryCells: number;
  claimCode: string;
  claimUrl: string;
  firmwareVersion: string;
  robotId: string;
  robotType: string;
  unitCode: string;
}) {
  return [
    `RoboForge Beta Kit: ${input.unitCode}`,
    "",
    `Robot ID: ${input.robotId}`,
    `Robot type: ${input.robotType}`,
    `Firmware: ${input.firmwareVersion}`,
    "Protocol: v1",
    `Battery cells: ${input.batteryCells}S`,
    `Local Wi-Fi SSID: ${input.apSsid}`,
    `Local Wi-Fi password: ${input.apPassword}`,
    "",
    "Owner claim:",
    input.claimUrl,
    input.claimCode,
    "",
    "Flash checklist:",
    "1. Paste the generated config into firmware/include/config.h.",
    "2. From app/, run npm run build:device.",
    "3. From firmware/, run pio run --target upload and pio run --target uploadfs.",
    "4. Join the robot Wi-Fi and run the non-driving protocol check.",
    "5. Raise the wheels before running the drive check.",
  ].join("\n");
}

export async function createClaimKitAction(
  _previousState: ClaimKitState,
  formData: FormData,
): Promise<ClaimKitState> {
  const supabase = await createServerSupabaseClient();

  if (!supabase) {
    return {
      ...initialClaimKitState,
      error: "Supabase is not configured.",
    };
  }

  const expiresAtValue = formValue(formData, "expiresAt");
  const expiresAtDate = expiresAtValue ? new Date(expiresAtValue) : null;

  if (expiresAtDate && Number.isNaN(expiresAtDate.getTime())) {
    return {
      ...initialClaimKitState,
      error: "Choose a valid expiry date.",
    };
  }

  const expiresAt = expiresAtDate ? expiresAtDate.toISOString() : null;
  const batteryCells = Number(formValue(formData, "batteryCells") || "2");
  const robotType = normalizeRobotType(formValue(formData, "robotType") || "rover");
  const firmwareVersion = normalizeFirmwareVersion(formValue(formData, "firmwareVersion"));

  if (![1, 2].includes(batteryCells)) {
    return {
      ...initialClaimKitState,
      error: "Choose 1S or 2S for the first Rover beta firmware.",
    };
  }

  const requestedApPassword = formValue(formData, "apPassword");

  if (
    requestedApPassword &&
    (requestedApPassword.length < 8 || requestedApPassword.length > 63)
  ) {
    return {
      ...initialClaimKitState,
      error: "Wi-Fi AP password must be 8-63 characters.",
    };
  }

  const { data, error } = await supabase.rpc("create_robot_claim_kit", {
    input_board_type: formValue(formData, "boardType") || "esp32",
    input_display_name: formValue(formData, "displayName") || null,
    input_expires_at: expiresAt,
    input_firmware_version: firmwareVersion,
    input_robot_type: robotType,
    input_unit_code: formValue(formData, "unitCode"),
  });

  if (error) {
    return {
      ...initialClaimKitState,
      error: actionErrorMessage(error.message),
    };
  }

  const kit = data as {
    claimCode: string;
    expiresAt: string | null;
    robotId: string;
    unitCode: string;
  };
  const apPassword = requestedApPassword || generateApPassword(kit.unitCode);
  const apSsid = `RoboForge-${kit.unitCode}`.slice(0, 31);
  const claimUrl = `${await getBaseUrl()}/dashboard?claim=${encodeURIComponent(
    kit.claimCode,
  )}`;
  const qrDataUrl = await QRCode.toDataURL(claimUrl, {
    errorCorrectionLevel: "M",
    margin: 2,
    width: 320,
  });

  const firmwareConfig = buildFirmwareConfig({
    apPassword,
    batteryCells,
    firmwareVersion,
    robotType,
    unitCode: kit.unitCode,
  });
  const localCheckCommand =
    "node scripts/rover-protocol-check.mjs --base-url=http://192.168.4.1";
  const raisedWheelCheckCommand = "node scripts/rover-protocol-check.mjs --raised-wheels";
  const kitManifest = buildKitManifest({
    apPassword,
    apSsid,
    batteryCells,
    claimCode: kit.claimCode,
    claimUrl,
    firmwareVersion,
    robotId: kit.robotId,
    robotType,
    unitCode: kit.unitCode,
  });

  const { error: deviceUpdateError } = await supabase
    .from("robot_devices")
    .update({
      ap_ssid: apSsid,
      battery_config: {
        calibration: 1,
        cells: batteryCells,
      },
      firmware_version: firmwareVersion,
      protocol_version: "v1",
    })
    .eq("robot_id", kit.robotId);

  revalidatePath("/admin");

  return {
    error: deviceUpdateError
      ? `Claim kit was created, but device metadata did not update: ${deviceUpdateError.message}`
      : null,
    kit: {
      ...kit,
      claimUrl,
      firmwareConfig,
      kitManifest,
      localCheckCommand,
      raisedWheelCheckCommand,
      qrDataUrl,
    },
    ok: true,
  };
}

export async function saveHardwareProfileAction(
  _previousState: HardwareProfileState,
  formData: FormData,
): Promise<HardwareProfileState> {
  const supabase = await createServerSupabaseClient();

  if (!supabase) {
    return {
      ...initialHardwareProfileState,
      error: "Supabase is not configured.",
    };
  }

  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return {
      ...initialHardwareProfileState,
      error: "Login is required.",
    };
  }

  const robotId = formValue(formData, "robotId");

  if (!robotId) {
    return {
      ...initialHardwareProfileState,
      error: "Choose a robot kit first.",
    };
  }

  const batteryCells = Number(formValue(formData, "batteryCells") || "0");
  const readinessStatus = normalizeReadinessStatus(
    formValue(formData, "readinessStatus"),
  );
  const hardwareProfile = {
    batteryCells: Number.isFinite(batteryCells) && batteryCells > 0 ? batteryCells : null,
    batteryChemistry: formValue(formData, "batteryChemistry") || null,
    boardModel: formValue(formData, "boardModel") || null,
    hasFuse: formBoolean(formData, "hasFuse"),
    hasPowerSwitch: formBoolean(formData, "hasPowerSwitch"),
    motorChannels: formValue(formData, "motorChannels") || "differential_drive",
    motorDriver: formValue(formData, "motorDriver") || null,
    notes: formValue(formData, "notes") || null,
    wiringStatus: formValue(formData, "wiringStatus") || "unknown",
  };

  const missingRequired = [
    hardwareProfile.boardModel,
    hardwareProfile.motorDriver,
    hardwareProfile.batteryChemistry,
    hardwareProfile.batteryCells,
  ].some((value) => !value);

  if (
    readinessStatus !== "needs_details" &&
    readinessStatus !== "blocked" &&
    missingRequired
  ) {
    return {
      ...initialHardwareProfileState,
      error:
        "Board, motor driver, battery chemistry, and cell count are required before marking the kit ready.",
    };
  }

  const { error } = await supabase
    .from("robot_devices")
    .update({
      battery_config: {
        chemistry: hardwareProfile.batteryChemistry,
        cells: hardwareProfile.batteryCells,
      },
      board_type: hardwareProfile.boardModel ?? "unknown",
      hardware_profile: hardwareProfile,
      readiness_status: readinessStatus,
      updated_at: new Date().toISOString(),
    })
    .eq("robot_id", robotId);

  if (error) {
    return {
      ...initialHardwareProfileState,
      error: error.message,
    };
  }

  await supabase.from("robot_events").insert({
    event_type: "hardware_profile_updated",
    message: `Ops updated hardware profile: ${readinessStatus}.`,
    metadata: hardwareProfile,
    robot_id: robotId,
    severity: readinessStatus === "blocked" ? "warning" : "info",
    user_id: user.id,
  });

  revalidatePath("/admin");

  return {
    error: null,
    ok: true,
  };
}
