import type { KitManifest, ModuleManifest } from "./roboforge-contracts";

export const embeddedRoverKitManifest = {
  manifestVersion: "0.1",
  kitId: "rf.kit.rover-01.beta",
  displayName: "RoboForge Rover-01 Beta Kit",
  robotType: "rover",
  protocolVersion: "v1",
  requiredModuleIds: [
    "rf.brain.esp32.devkit-v1",
    "rf.actuator.motor_driver.l298n",
    "rf.actuator.motor.tt_dc_pair",
    "rf.power.pack.18650_2s",
  ],
  optionalSlots: [
    {
      slotId: "front-distance",
      displayName: "Front distance sensor",
      acceptedModuleTypes: ["sensor"],
      acceptedBuses: ["i2c"],
      recommendedModuleIds: ["rf.sensor.distance.vl53l0x"],
    },
  ],
  profileDefaults: {
    profileVersion: "0.1",
    mechanism: {
      drive: "differential_drive",
      motorDriver: "L298N dual H-bridge",
    },
    muscle: {
      actuators: ["left_drive_motor", "right_drive_motor"],
    },
    communication: {
      mode: "local_wifi",
      localUrl: "http://192.168.4.1",
    },
    safety: {
      requiresArm: true,
      raisedWheelTestRequired: true,
      readiness: "ready_for_bench",
    },
  },
  firmware: {
    targetBoard: "esp32dev",
    framework: "arduino",
    configTemplate: "hardware/templates/esp32_rover_config.h.mustache",
    currentVersion: "0.1.0",
  },
  safetyGates: [
    "hardware_profile_complete",
    "power_switch_verified",
    "fuse_or_protected_pack_verified",
    "bench_protocol_check",
    "raised_wheel_test_passed",
  ],
} satisfies KitManifest;

export const embeddedModuleManifests = [
  {
    manifestVersion: "0.1",
    moduleId: "rf.actuator.motor.tt_dc_pair",
    moduleType: "actuator",
    displayName: "TT DC Motor Pair",
    bus: "mechanical",
    capabilities: ["differential_drive_motion"],
    requiresFirmware: ">=0.1.0",
    compatibleRobotTypes: ["rover"],
    safetyNotes: [
      "Run first drive tests with wheels raised.",
      "Verify left and right channel mapping before floor tests.",
    ],
    metadata: {
      motorCount: 2,
    },
  },
  {
    manifestVersion: "0.1",
    moduleId: "rf.actuator.motor_driver.l298n",
    moduleType: "actuator",
    displayName: "L298N Dual H-Bridge Motor Driver",
    bus: "gpio",
    capabilities: ["dual_motor_drive", "pwm_speed_control"],
    requiresFirmware: ">=0.1.0",
    compatibleRobotTypes: ["rover"],
    safetyNotes: [
      "Use for prototype validation only; confirm current and heat before floor tests.",
      "Remove ENA/ENB jumpers when firmware controls PWM.",
    ],
    metadata: {
      defaultPins: {
        ena: 25,
        in1: 26,
        in2: 27,
        enb: 33,
        in3: 32,
        in4: 14,
      },
    },
  },
  {
    manifestVersion: "0.1",
    moduleId: "rf.brain.esp32.devkit-v1",
    moduleType: "brain",
    displayName: "ESP32 DevKit V1",
    bus: "wifi",
    capabilities: ["local_wifi_ap", "http_control_api", "littlefs_cockpit"],
    requiresFirmware: ">=0.1.0",
    compatibleRobotTypes: ["rover"],
    safetyNotes: [
      "Keep live motor commands on the robot Wi-Fi link.",
      "Use a unique AP password per physical kit.",
    ],
    metadata: {
      platformioBoard: "esp32dev",
      framework: "arduino",
    },
  },
  {
    manifestVersion: "0.1",
    moduleId: "rf.power.pack.18650_2s",
    moduleType: "power",
    displayName: "2S 18650 Li-ion Pack",
    bus: "power",
    capabilities: ["battery_power", "voltage_telemetry"],
    requiresFirmware: ">=0.1.0",
    compatibleRobotTypes: ["rover"],
    safetyNotes: [
      "Use an accessible power switch.",
      "Use a fuse, protected pack, or BMS before floor tests.",
      "Calibrate battery voltage against a multimeter.",
    ],
    metadata: {
      chemistry: "li-ion",
      cells: 2,
    },
  },
  {
    manifestVersion: "0.1",
    moduleId: "rf.sensor.distance.vl53l0x",
    moduleType: "sensor",
    displayName: "VL53L0X Distance Sensor",
    bus: "i2c",
    capabilities: ["distance_mm", "mission_telemetry", "obstacle_awareness"],
    requiresFirmware: ">=0.2.0",
    compatibleRobotTypes: ["rover"],
    safetyNotes: [
      "Mount away from wheel path.",
      "Treat readings as guidance, not a safety stop, until behavior tests exist.",
    ],
    metadata: {
      defaultAddress: "0x29",
    },
  },
] satisfies ModuleManifest[];

export const embeddedEsp32RoverConfigTemplate = `#pragma once

// Generated by RoboForge Ops for this physical kit.
#define ROBOFORGE_UNIT_CODE "{{UNIT_CODE}}"
#define ROBOFORGE_AP_PASSWORD "{{AP_PASSWORD}}"
#define ROBOFORGE_BATTERY_CELLS {{BATTERY_CELLS}}
#define ROBOFORGE_BATTERY_CALIBRATION 1.000f
#define ROBOFORGE_FIRMWARE_VERSION "{{FIRMWARE_VERSION}}"
#define ROBOFORGE_PROTOCOL_VERSION "{{PROTOCOL_VERSION}}"
#define ROBOFORGE_ROBOT_TYPE "{{ROBOT_TYPE}}"

// Rover-01 standardized wiring.
#define ROBOFORGE_PIN_ENA 25
#define ROBOFORGE_PIN_IN1 26
#define ROBOFORGE_PIN_IN2 27
#define ROBOFORGE_PIN_ENB 33
#define ROBOFORGE_PIN_IN3 32
#define ROBOFORGE_PIN_IN4 14
#define ROBOFORGE_PIN_BATTERY_ADC 34`;
