#pragma once

#define ROBOFORGE_FIRMWARE_VERSION "0.2.0-mqtt-agent"
#define ROBOFORGE_TOPIC_PREFIX "rf"
#define ROBOFORGE_DEFAULT_MQTT_HOST "mqtt.roboforge.app"
#define ROBOFORGE_DEFAULT_MQTT_PORT 8883
#define ROBOFORGE_DEFAULT_MQTT_TLS true
#define ROBOFORGE_DEFAULT_WIFI_SSID ""
#define ROBOFORGE_DEFAULT_WIFI_PASSWORD ""
#define ROBOFORGE_DEFAULT_TOKEN ""

#define ROBOFORGE_BATTERY_CELLS 2
#define ROBOFORGE_BATTERY_CALIBRATION 1.000f
#define ROBOFORGE_BATTERY_DIVIDER_TOP_OHMS 100000.0f
#define ROBOFORGE_BATTERY_DIVIDER_BOTTOM_OHMS 33000.0f

#define ROBOFORGE_PIN_ENA 25
#define ROBOFORGE_PIN_IN1 26
#define ROBOFORGE_PIN_IN2 27
#define ROBOFORGE_PIN_ENB 33
#define ROBOFORGE_PIN_IN3 32
#define ROBOFORGE_PIN_IN4 17
#define ROBOFORGE_PIN_BATTERY_ADC 34

#define ROBOFORGE_PIN_ULTRASONIC_TRIG 4
#define ROBOFORGE_PIN_ULTRASONIC_ECHO 16
